on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build API Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_APP_IMAGE_NAME_API: "ghcr.io/whiletrue-industries/odds/odds-server"
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u whiletrue-industries --password-stdin &&\

          if docker pull "${DOCKER_APP_IMAGE_NAME_API}:latest"; then
            CACHE_FROM_ARG="--cache-from ${DOCKER_APP_IMAGE_NAME_API}:latest"
          else
            CACHE_FROM_ARG=""
          fi &&\
          docker build $CACHE_FROM_ARG --build-arg VERSION=${GITHUB_SHA} -t app -f docker/api-server/Dockerfile . &&\
          docker tag app "${DOCKER_APP_IMAGE_NAME_API}:${GITHUB_SHA}" &&\
          docker push "${DOCKER_APP_IMAGE_NAME_API}:${GITHUB_SHA}" &&\
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            docker tag app "${DOCKER_APP_IMAGE_NAME_API}:latest" &&\
            docker push "${DOCKER_APP_IMAGE_NAME_API}:latest"
          fi
      - name: Build UI Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_APP_IMAGE_NAME_UI: "ghcr.io/whiletrue-industries/odds/odds-ui"
        run: |
          if docker pull "${DOCKER_APP_IMAGE_NAME_UI}:latest"; then
            CACHE_FROM_ARG="--cache-from ${DOCKER_APP_IMAGE_NAME_UI}:latest"
          else
            CACHE_FROM_ARG=""
          fi &&\
          docker build $CACHE_FROM_ARG --build-arg VERSION=${GITHUB_SHA} -t fe -f docker/ui/Dockerfile . &&\
          docker tag fe "${DOCKER_APP_IMAGE_NAME_UI}:${GITHUB_SHA}" &&\
          docker push "${DOCKER_APP_IMAGE_NAME_UI}:${GITHUB_SHA}" &&\
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            docker tag fe "${DOCKER_APP_IMAGE_NAME_UI}:latest" &&\
            docker push "${DOCKER_APP_IMAGE_NAME_UI}:latest"
          fi
      - name: Build PROXY Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_APP_IMAGE_NAME_PROXY: "ghcr.io/whiletrue-industries/odds/odds-proxy"
        run: |
          docker build --build-arg VERSION=${GITHUB_SHA} -t pr -f docker/proxy/Dockerfile . &&\
          docker tag pr "${DOCKER_APP_IMAGE_NAME_PROXY}:${GITHUB_SHA}" &&\
          docker push "${DOCKER_APP_IMAGE_NAME_PROXY}:${GITHUB_SHA}" &&\
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            docker tag pr "${DOCKER_APP_IMAGE_NAME_PROXY}:latest" &&\
            docker push "${DOCKER_APP_IMAGE_NAME_PROXY}:latest"
          fi
      - name: Build PROXY-FETCHER Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_APP_IMAGE_NAME_FETCHER_PROXY: "ghcr.io/whiletrue-industries/odds/odds-fetcher-proxy"
        run: |
          cd utils/fetcher-proxy &&\
          docker build --build-arg VERSION=${GITHUB_SHA} -t pf  . &&\
          docker tag pf "${DOCKER_APP_IMAGE_NAME_FETCHER_PROXY}:${GITHUB_SHA}" &&\
          docker push "${DOCKER_APP_IMAGE_NAME_FETCHER_PROXY}:${GITHUB_SHA}" &&\
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            docker tag pf "${DOCKER_APP_IMAGE_NAME_FETCHER_PROXY}:latest" &&\
            docker push "${DOCKER_APP_IMAGE_NAME_FETCHER_PROXY}:latest"
          fi
